version: '3.5'

services:
  webapi-dev:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - src/.env
    environment:
      - APP_HOST=0.0.0.0
      # Intern port
      - APP_PORT=5000
      - FLASK_ENV=development
    ports:
      - '5001:5000'
  webapi-prod:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - src/.env
    environment:
      - APP_HOST=0.0.0.0
      # Intern port
      - APP_PORT=5000
      - FLASK_ENV=production
    ports:
      - '5002:5000'