version: '3.5'

services:
  webapi-dev:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - src/.env
    environment:
      - APP_HOST=0.0.0.0
      # Intern port
      - APP_PORT=5000
      - FLASK_ENV=development
      - URL_PREFIX=/test
    ports:
      - '5001:5000'
  webapi-prod:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - src/.env
    environment:
      # Intern port
      - APP_PORT=5000
      - FLASK_ENV=production
      - URL_PREFIX=/balena
    volumes:
      - /home/tobias/.letsencrypt/config/live/contabo.tobias-blaufuss.de/cert.pem:/ssl/cert.pem
      - /home/tobias/.letsencrypt/config/live/contabo.tobias-blaufuss.de/privkey.pem:/ssl/privkey.pem
    ports:
      - '5002:5000'
