#!/bin/sh

location=$1

# Optional: dev, prod
mode=$2

if [[ -z "$location" ]]; then
    echo "Provide a location as first parameter."
    exit 1
fi

if [[ -z "$mode" && -z "$FLASK_ENV" ]]; then
    mode="dev"
elif [[ "$mode" = "dev" || "$FLASK_ENV" = "development" ]]; then
    mode="dev"
elif [[ "$mode" = "prod" || "$FLASK_ENV" = "production" ]]; then
    mode="prod"
fi

# Apply defaults environment variables
export SRC_DIR=${SRC_DIR:-"src"}
export WORK_DIR=${WORK_DIR:-"$CWD"}
export APP_HOST=${APP_HOST:-"localhost"}
export APP_PORT=${APP_PORT:-"5000"}
export APP_PROCESSES=${APP_PROCESSES:-"2"}
export APP_THREADS=${APP_THREADS:-"2"}
export MOUNT_URL=${MOUNT_URL:-"/api"}

if [ "$mode" = "dev" ]; then
    export FLASK_ENV="development"
elif [ "$mode" = "prod" ]; then
    export FLASK_ENV="production"
    export BALENA_TOKEN=${BALENA_TOKEN:-"<specify token here>"}
    export APP_HOST=${APP_HOST:-"0.0.0.0"}
else
    echo "Unknown mode: '$mode'. Use one of the following modes: dev, prod"
    exit 1
fi